# Generated by Django 5.0.4 on 2024-07-05 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('number', models.IntegerField()),
                ('pincode', models.IntegerField(null=True)),
                ('date', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('s_name', models.CharField(max_length=200, null=True)),
                ('s_price', models.IntegerField(null=True)),
                ('payment_mode', models.CharField(default='Razor_pay', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='empregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(default='default_password', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(default=1234567890)),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.IntegerField(default=123456)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(default='default_password', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('img', models.FileField(upload_to='')),
                ('phone', models.IntegerField(default=1234567890)),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.IntegerField(default=123456)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=300)),
                ('price', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ur_name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('service_name', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('pincode', models.IntegerField(max_length=200, null=True)),
                ('number', models.IntegerField(max_length=50, null=True)),
                ('date', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Finished', 'Finished'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='pending', max_length=150, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.services')),
            ],
        ),
    ]
